# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_id', models.CharField(max_length=50, unique=True)),
                ('crash_path', models.CharField(help_text='The path to the original crash report on the file system.', max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=100, null=True)),
                ('vendor_id', models.CharField(max_length=100, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Version')),
            ],
        ),
    ]
