# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crashsubmit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(help_text='The name of the product.', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_id', models.CharField(max_length=50, unique=True)),
                ('crash_path', models.CharField(help_text='The path to the original crash report on the file system.', max_length=200)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(max_length=100, null=True)),
                ('vendor_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_version', models.SmallIntegerField()),
                ('minor_version', models.SmallIntegerField()),
                ('micro_version', models.SmallIntegerField()),
                ('patch_version', models.SmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashsubmit.Product')),
            ],
        ),
        migrations.AddField(
            model_name='uploadedcrash',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashsubmit.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('product', 'major_version', 'minor_version', 'micro_version', 'patch_version')]),
        ),
    ]
