# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashsubmit', '0002_auto_20151214_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
