# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0011_auto_20151228_1517'),
        ('crashsubmit', '0003_version_featured'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AlterField(
            model_name='uploadedcrash',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Version'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
