# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField()),
                ('comment', models.TextField(help_text='A comment explaining where these symbols are comming from')),
                ('files', models.TextField(help_text='A list with all the files contained in that upload')),
            ],
        ),
    ]
