# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolsupload',
            name='system_symbols',
            field=models.BooleanField(default=False, help_text='This contains system symbols and not LibreOffice symbols'),
        ),
    ]
