# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_symbolsupload_system_symbols'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_file', models.CharField(db_index=True, max_length=255)),
                ('debug_id', models.CharField(db_index=True, max_length=100)),
                ('code_id', models.CharField(db_index=True, max_length=100)),
                ('code_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MissingSymbolConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField()),
            ],
        ),
    ]
