# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(help_text=b'The name of the product.', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_version', models.SmallIntegerField()),
                ('minor_version', models.SmallIntegerField()),
                ('micro_version', models.SmallIntegerField()),
                ('patch_version', models.SmallIntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('product', 'major_version', 'minor_version', 'micro_version', 'patch_version')]),
        ),
    ]
