# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='version',
            index_together=set([('major_version', 'minor_version', 'micro_version', 'patch_version')]),
        ),
    ]
