# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('major_version', 'minor_version', 'micro_version', 'patch_version')]),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
