# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Version')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedCrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_id', models.CharField(max_length=100, unique=True)),
                ('upload_time', models.DateTimeField()),
                ('process_time', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(default=None, max_length=100, null=True)),
                ('vendor_id', models.CharField(default=None, max_length=100, null=True)),
                ('os_name', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('osx', 'OSX'), ('android', 'Android'), ('ios', 'IOS')], max_length=10)),
                ('os_detail', models.CharField(default='', max_length=100)),
                ('cpu_architecture', models.CharField(max_length=20)),
                ('cpu_info', models.CharField(default='', max_length=100)),
                ('crash_cause', models.CharField(default='SIGSEGV', max_length=35)),
                ('crash_address', models.CharField(default='0x0', max_length=100)),
                ('crash_thread', models.SmallIntegerField(default=0, help_text='The id of the thread that caused the crash')),
                ('modules', models.TextField()),
                ('crashing_thread', models.TextField()),
                ('threads', models.TextField()),
                ('raw', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('signature', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_observed', models.DateTimeField()),
                ('last_observed', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Signature'),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='crashcount',
            unique_together=set([('version', 'date')]),
        ),
    ]
