# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedcrash',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='processedcrash',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='additional_data',
            field=models.TextField(default='{}'),
        ),
    ]
