# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_graphicdevice_processedcrash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedcrash',
            name='backtrace',
        ),
        migrations.RemoveField(
            model_name='processedcrash',
            name='graphic_device',
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='cpu_architecture',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='cpu_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='crash_address',
            field=models.CharField(default='0x0', max_length=100),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='crash_cause',
            field=models.CharField(default='SIGSEGV', max_length=35),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='crash_thread',
            field=models.SmallIntegerField(default=0, help_text='The id of the thread that caused the crash'),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='modules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='os_detail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='threads',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GraphicDevice',
        ),
    ]
