# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20160526_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_nr', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='signature',
            name='bugs',
            field=models.ManyToManyField(to='processor.BugReport'),
        ),
    ]
