# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20151215_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedcrash',
            name='crash_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashsubmit.UploadedCrash', to_field='crash_id', unique=True),
        ),
    ]
