# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20160608_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
