# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_auto_20160609_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
