# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_auto_20160614_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
