# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0006_auto_20151216_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('signature', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_observed', models.DateTimeField()),
                ('last_observed', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='processedcrash',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Signature'),
        ),
    ]
