# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_auto_20151219_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedcrash',
            name='raw',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
