# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crashsubmit', '0003_version_featured'),
        ('processor', '0008_processedcrash_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crashsubmit.Version')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='crashcount',
            unique_together=set([('version', 'date')]),
        ),
    ]
