# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0010_processedcrash_crashing_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashcount',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Version'),
        ),
    ]
