# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('processor', '0011_auto_20151228_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedcrash',
            name='device_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='process_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 28, 15, 40, 41, 472606, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 28, 15, 40, 50, 520676, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='vendor_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processedcrash',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Version'),
        ),
        migrations.AlterField(
            model_name='processedcrash',
            name='crash_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='processedcrash',
            name='os_name',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('osx', 'OSX'), ('android', 'Android'), ('ios', 'IOS')], max_length=10),
        ),
    ]
